source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "mongoid", "2.0.0.beta.20"
gem "bson_ext", "1.1.5"
gem "ruby-smpp", "0.4.0" 
gem "mongoid-tree", :require => 'mongoid/tree'
gem "memcache"
gem "dalli"
